### PR TITLE
Feature/new datasets

### PR DESCRIPTION
**Pull request by michalk8**
@Marius1311 can you please update the docstrings?
Also, currently the figshare is private, so downloads won't work.

### CODE REVIEW

**Review by MUCDK — APPROVED** [review]
Can we remove TedSim then?

**Comment by MUCDK** [comment]
> @Marius1311 can you please update the docstrings? Also, currently the figshare is private, so downloads won't work.

Why is it private? You do have access to moscot figshare, don't you? or do I have to make it public then?

**Comment by michalk8** [comment]
> Can we remove TedSim then?

I don't know, will create an issues for this.

Merging this not to block @Marius1311 .

**Comment by Marius1311** [comment]
> Can we remove TedSim then?

No, we're just adding additional datasets, we cannot remove TedSim.

**Pull request merged**
