### PR TITLE
test example in CI (new)

### PR DESCRIPTION
**Pull request by ArinaDanilina**
#552

### CODE REVIEW

**Comment by MUCDK** [comment]
@giovp @ArinaDanilina what's the state here?

**Comment by giovp** [comment]
super cool @selmanozleyen , just fyi I think it's fine to just run for now notebooks in the example folder. Looking forward to updates!

**Comment by selmanozleyen** [comment]
thanks @giovp, current setup should be a functional example. Some notebooks do give errors.

First,I tried to do it the way @michalk8 suggested here  https://github.com/theislab/moscot/issues/552#issuecomment-1596752234 (by building docs) but it required messing with the metadata of nb files and the errors were written to log files. For now jupytext seemed easier.

**Comment by giovp** [comment]
I think it's a jax update https://jax.readthedocs.io/en/latest/changelog.html , I think we need to pin down jax for the time being until ott-jax supports it, cc @MUCDK @michalk8

**Comment by MUCDK** [comment]
Isn't the example failing according to the tests?

**Comment by MUCDK** [comment]
@ArinaDanilina can you check the failing example, please?

**Comment by giovp** [comment]
thanks @ArinaDanilina , @selmanozleyen , still some issues in notebooks, but should be easy fix!

**Review by giovp — APPROVED** [review]

**Pull request merged**
